export const about = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Hi there!👋',
    description: "Myself, Harshal. A passionate innovator with a hunger for challenges and a track record of turning ideas into reality. Currently seeking new opportunities to apply my skills and expertise in a dynamic professional environment. Let's create something extraordinary together!",
    imgStart: true,
    img: require('../../images/university.png'),
    darkText: true,
    buttonExist: false,
    liExist: false,
}

export const workUofM = {
    id: 'workUofM',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Frontend Web Developer 💻',
    description: "As a Frontend Web Developer at the University of Manitoba, I spearheaded a collaborative effort, leading a team of designers to create a groundbreaking website for the School of Arts. This platform showcased the artistic endeavors of the graduating class of 2020-2021 and garnered an impressive 5000+ visits. Notably, this initiative marked the inception of the first-ever art exhibition website in the history of the University of Manitoba, underscoring innovation and excellence in digital presentation.",
    imgStart: true,
    img: require('../../images/university.png'),
    link: "https://www.soaexhibitions.ca",
    darkText: true,
    buttonExist: true,
    buttonLabel: 'Website',
    dark: false,
    primary: true,
    li1: "Front End Development:- HTML, CSS & Javascript",
    li2: "Animation:- SVG animations",
    li3: "UI/UX Design:- Adobe Illustrator",
    liExist: true,
}

export const work = {
    id: 'work',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Cloud DevOps Engineer 💻',
    description: "I served as a Cloud DevOps Engineer at Nutrien, contributing to impactful projects that reached millions globally. From implementing automation strategies to seamlessly integrating SonarQube into our CI/CD pipeline, managing intricate front-end and back-end projects, to meticulously documenting technical processes, my experience has been a dynamic journey of continuous learning. Eager to build on this foundation and explore new horizons in the ever-evolving tech landscape.",
    imgStart: true,
    img: require('../../images/Nutrien_Logo.png'),
    darkText: true,
    buttonExist: false,
    buttonLabel: 'Website',
    dark: false,
    primary: true,
    li1: "Languages & Frameworks:- JavaScript, TypeScript, Bash Script, C#, React, Jest, ASP.NET CORE, CSS, HTML, NodeJS",
    li2: "Tools:- AWS Resources (Lambda, S3, CloudFront…), Splunk, CircleCI, Jira, Postman, SonarQube, Git",
    li3: "Databases:- PostgreSQL, DynamoDB, RDS",
    liExist: true,
}