export const about = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Hi there!👋',
    description: "Myself, Harshal Bhalerao. I'm in my last year of Computer Science Bachelor's Degree at University of Manitoba in Winnipeg, Manitoba.",
    imgStart: false,
    img: require('../../images/university.png'),
    darkText: true,
    buttonExist: false,
    liExist: false,
}

export const work = {
    id: 'work',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Work Experience: 🌞 Summer 2021 💻',
    description: "Worked Part-time at University of Manitoba for School of Arts as a Web Developer. Created an entire website with designers from Faculty of Arts. The website exhibited the best art from the Graduating School Of Art's class of 2020-2021. The website has been visited by more than 300 people.",
    imgStart: true,
    img: require('../../images/university.png'),
    link: "https://www.soaexhibitions.ca",
    darkText: true,
    buttonExist: true,
    buttonLabel: 'Website',
    dark: false,
    primary: true,
    langUsed: "Front End Development:- HTML, CSS & Javascript",
    animationUsed: "Animation:- SVG animations",
    uiUsed: "UI/UX Design:- Adobe Illustrator",
    liExist: true,
}