export const about = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Hi there!👋',
    description: "Myself, Harshal. I am a 4th year Computer Science student at University of Manitoba who is currently a DevOps Engineering Intern at Nutrien.",
    imgStart: false,
    img: require('../../images/university.png'),
    darkText: true,
    buttonExist: false,
    liExist: false,
}

export const workUofM = {
    id: 'workUofM',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'Frontend Web Dev💻 (May 2021- Aug 2021)',
    description: "Worked as a Frontend Web Developer at University of Manitoba. Led a team of 2 designers and built a website for School of Arts at University of Manitoba for exhibiting art created by students of graduating class 2020-2021. The website has more than 500+ visits.",
    imgStart: false,
    img: require('../../images/university.png'),
    link: "https://www.soaexhibitions.ca",
    darkText: true,
    buttonExist: true,
    buttonLabel: 'Website',
    dark: false,
    primary: true,
    li1: "Front End Development:- HTML, CSS & Javascript",
    li2: "Animation:- SVG animations",
    li3: "UI/UX Design:- Adobe Illustrator",
    liExist: true,
}

export const work = {
    id: 'work',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    headLine: 'DevOps Engineer 💻 (Jan 2022 - Present)',
    description: "Currently I work as a DevOps Engineer at Nutrien. I work on awesome projects which impact millions of people across the globe. From automation to integrating SonarQube in CI/CD pipeline, from complex front-end and back-end projects to writing technical documentations. I have learnt a lot and want to keep learning.",
    imgStart: true,
    img: require('../../images/Nutrien_Logo.png'),
    darkText: true,
    buttonExist: false,
    buttonLabel: 'Website',
    dark: false,
    primary: true,
    li1: "Languages & Frameworks:- TypeScript, Bash Script, C#, React, Jest, ASP.NET CORE",
    li2: "Tools:- AWS Resources (Lambda, S3, CloudFront…), Splunk, CircleCI, Jira, Postman, SonarQube",
    li3: "Databases:- PostgreSQL, DynamoDB, RDS",
    liExist: true,
}